import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { Navbar } from "../components/common/Navbar";
import { Footer } from "../components/common/Footer";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Toaster } from "sonner";

import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Ecommerce Template",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <div className="bg-black text-white text-center p-2.5 flex justify-center items-center">
          <p className="text-sm md:text-lg">
            Signup and get 20% off on your first order
          </p>
          <a href="/signup" className="text-white underline ml-1.5">
            <p className="text-sm md:text-lg">Sign Up Now</p>
          </a>
        </div>
        <Navbar />
        <main className="w-full flex flex-col justify-center items-center">
          <div className="w-full">{children}</div>
          <Toaster position="top-right" />
          <Analytics />
          <SpeedInsights />
        </main>
        <Footer />
      </body>
    </html>
  );
}
